#this script uses the models generated by Statistical_analysis
#and generates hypothetical subjects and predicts ECog values for them
#Then it plots these predicted values


#define the range of values from memory or Executive function for which to predict ECog
#In some cases I use specific ranges to dismiss parts at which the data is sparse (e.g at exec function>1.5 for age=85)
predrange<-c(-2.5,-1,0,0.5,1,2,2.5)



FigureList<-list()
#below I'm generating hypothetical data for different exposures 
#(memory, executive function (with spline), and exec without spline (coming))


########################################################################
#base model: 
xba<- rep(predrange,3)

newDFage <- data.frame(
  memory=xba,
  ex_function=xba,
  AGE_75_d=rep(c(-1,0,1),each=7))

########################################################################
#race model
xre<- rep(predrange,4)
newDFrace <- data.frame(
  memory=xre,
  ex_function=xre,
  AGE_75_d=rep(c(0),each=28), 
  race=rep(c("Non-Latino-White","Black","Latino","Asian"),each=7))

########################################################################
##gender model
xge<- rep(predrange,2)
newDFgender <- data.frame(
  memory=xge,
  ex_function=xge,
  AGE_75_d=rep(c(0),each=14),
  GENDER=rep(c("Man","Woman"),each=7))

########################################################################
##education
xed<- rep(predrange,3)

newDFedu <- data.frame(
  memory=xed,
  ex_function=xed,
  AGE_75_d=rep(c(0),each=21),
  yrEDU=rep(c(-4,0,4),each=7),
  race=rep("Non-Latino-White",21))

########################################################################
##familial dementia
xfh<- rep(predrange,2)
newDFfhist <- data.frame(
  memory=xfh,
  ex_function=xfh,
  AGE_75_d=rep(c(0),each=14),
  F_Hist=rep(c(0,1),each=7))

########################################################################
#depression
xdpr<- rep(predrange,3)
newDFdepr <- data.frame(
  memory=xdpr,
  ex_function=xdpr,
  AGE_75_d=rep(c(0),each=21),
  depression_01=rep(c(-1,0,1),each=7),
  GENDER=rep(c("Woman"),each=21))

predggba_mem <- predict.lm(memfit[[1]],
                    newDFage, interval = "conf")
predggge_mem <- predict.lm(memfit[[2]],
                    newDFgender, interval = "conf")
predggra_mem <- predict.lm(memfit[[3]],
                    newDFrace, interval = "conf")
predgged_mem <- predict.lm(memfit[[4]],
                    newDFedu, interval = "conf")
predggfh_mem <- predict.lm(memfit[[5]],
                    newDFfhist, interval = "conf")
predggdpr_mem <- predict.lm(memfit[[6]],
                     newDFdepr, interval = "conf")
########################################################################

predggba <- predict.lm(results_execfun[[1]],
                       newDFage, interval = "conf")
predggge <- predict.lm(results_execfun[[2]],
                       newDFgender, interval = "conf")
predggra <- predict.lm(results_execfun[[3]],
                       newDFrace, interval = "conf")
predgged <- predict.lm(results_execfun[[4]],
                       newDFedu, interval = "conf")
predggfh <- predict.lm(results_execfun[[5]],
                       newDFfhist, interval = "conf")
predggdpr <- predict.lm(results_execfun[[6]],
                        newDFdepr, interval = "conf")


#########################################################################
#########################################################################
#GRAPHICS 
#########################################################################
#########################################################################
#setting ploting parameters

plots_list<-list()
BW<- 0 #Black&Withe version for printing (set to 0 for color)
textSize <- 11
PM<- margin(.2, 0.2, .8, .5, "cm")
limin <- 0
limax <- 0.6
xlim<-c(-2,2)
xlab="Episodic memory"
xmarks <- scale_x_continuous(breaks=seq(-2,2,0.5))

#plots for episodic memory
#base model with age only

#setting range to accomodate datasparsity

newDFageM<-cbind(newDFage,predggba_mem)
Ba_mem <- ggplot(data = newDFageM[1:20,])+
  geom_ribbon(aes(memory ,ymin=lwr,ymax=upr,
                  group=factor(AGE_75_d,levels = c(1,0,-1)),
                  fill=factor(AGE_75_d,levels = c(1,0,-1))),
              alpha=0.15)+
  geom_line(aes(memory ,fit,
                color=factor(AGE_75_d,
                             levels = c(1,0,-1)),
                linetype=factor(AGE_75_d,
                                levels = c(1,0,-1))),
            size=1)+ 
  #theme_()+
  ylab("Predicted log(ECog)")+
  xlab(xlab)+
  theme_classic2()+
  theme(legend.justification=c(1,0), 
        legend.position="top",#c(0.95,0.65),
        legend.direction = "horizontal",
        legend.text=element_text(size=textSize),
        legend.text.align=1,
        text = element_text(size = textSize),
        plot.margin = PM)+
  scale_color_discrete(name="Age (years)", 
                       labels = c("85","75","65"))+
  scale_linetype_discrete(name="Age (years)", 
                          labels = c("85","75","65"))+
  coord_cartesian(xlim = xlim, ylim = c(limin,limax), expand = FALSE,
                  default = FALSE, clip = "on")+
  xmarks+
  guides(fill = FALSE,
         linetype=FALSE,
         color=FALSE)
if (BW==1) {
  Ba_mem <- Ba_mem + scale_color_grey(start = 0, end = .8) + scale_fill_grey(start = 0, end = .8)
}
#plot.margin = margin(.5, .2, .8, .5, "cm")
FigureList[[1]]<-Ba_mem

#race/ethnicity

Ra_mem<-ggplot(data = newDFrace)+
  geom_ribbon(aes(xre,ymin=predggra_mem[,2],ymax=predggra_mem[,3],
                  group=race,fill=race),
              alpha=0.15)+
  geom_line(aes(xre,predggra_mem[,1],
                color=race,
                linetype=race),
            size=1)+ 
  theme_classic2()+
  ylab("Predicted log(ECog)")+
  xlab(xlab)+
  theme(legend.justification=c(1,0), 
        legend.position=c(.95,0.62),
        legend.title = element_blank(),
        legend.spacing = unit(.5, 'cm'),
        legend.direction = "vertical",
        legend.text=element_text(size=textSize),
        legend.text.align=0,
        legend.title.align=1,
        text = element_text(size = textSize),
        plot.margin = PM)+
  coord_cartesian(xlim = xlim, ylim = c(limin,limax), expand = FALSE,
                  default = FALSE, clip = "on")+xmarks+
  guides(fill = FALSE,
         linetype=FALSE,
         color=FALSE)
if (BW==1) {
  Ra_mem <- Ra_mem + scale_color_grey(start = 0, end = .8) + scale_fill_grey(start = 0, end = .9)
}

FigureList[[2]]<- Ra_mem

#gender
Ge_mem<-ggplot(data = newDFgender)+
  geom_ribbon(
    aes(xge,
        ymin=predggge_mem[,2],
        ymax=predggge_mem[,3],
        group=factor(GENDER,levels = c("Woman","Man")),
        fill=factor(GENDER,levels = c("Woman","Man"))),
    alpha=0.15)+
  geom_line(
    aes(xge,
        predggge_mem[,1],
        color=factor(GENDER,levels = c("Woman","Man")),
        linetype=factor(GENDER,levels = c("Woman","Man"))),
    size=1)+ 
  theme_classic2()+xmarks+
  ylab("Predicted log(ECog)")+
  xlab(xlab)+
  theme(legend.justification=c(1,0), 
        legend.position=c(0.95,0.70),
        legend.spacing = unit(.1,"cm"),
        legend.direction = "vertical",
        legend.text=element_text(size=textSize),
        legend.title.align=0,
        text = element_text(size = textSize),
        plot.margin = PM)+
  scale_linetype_discrete(name= "Gender",labels=c("Women","Men"))+
  scale_color_discrete(name= "Gender", labels=c("Women","Men"))+
  coord_cartesian(xlim = xlim, ylim = c(limin,limax), expand = FALSE,
                  default = FALSE, clip = "on")+
  guides(fill = FALSE,
         linetype=FALSE,
         color=FALSE)
if (BW==1) {
  Ge_mem <- Ge_mem + scale_color_grey(start = 0, end = .8) + scale_fill_grey(start = 0, end = .8)
}
FigureList[[3]]<-Ge_mem

#education duration
range<-c(1:5,8:21)
newDFeduM<-cbind(newDFedu,predgged_mem)
Ed_mem <- ggplot(data = newDFeduM[range,])+ 
  geom_ribbon(aes(xed[range],ymin=lwr,ymax=upr,
                  group=factor(yrEDU),
                  fill=factor(yrEDU)),
              alpha=0.15) +
  geom_line(aes(xed[range],fit,
                color=factor(yrEDU),
                linetype=factor(yrEDU)),
            size=1) + 
  theme_classic2()+xmarks+
  ylab("Predicted log(ECog)") + 
  xlab(xlab)+
  theme(legend.justification=c(1,0), 
        legend.position=c(.95,0.70),
        legend.direction = "vertical",
        legend.text=element_text(size=textSize),
        legend.title = element_text(size=textSize),
        legend.text.align=0,
        legend.title.align=1,
        text = element_text(size = textSize),
        plot.margin = PM)+
  scale_color_discrete(labels = c("8 ","12 ","16 "))+
  scale_linetype_discrete(labels = c("8 ","12 ","16 "))+
  coord_cartesian(xlim = xlim, ylim = c(limin,limax), expand = FALSE,
                  default = FALSE, clip = "on")+
  guides(fill = FALSE,
         linetype=FALSE,
         color=FALSE)
if (BW==1) {
  Ed_mem <- Ed_mem + scale_color_grey(start = 0, end = .8) + scale_fill_grey(start = 0, end = .8)
}
FigureList[[4]]<-Ed_mem

#Family history of dementia
Fh_mem <- ggplot(data = newDFfhist)+
  geom_ribbon(aes(xfh,ymin=predggfh_mem[,2],ymax=predggfh_mem[,3],
                  group=factor(F_Hist,levels = c(1,0)),
                  fill=factor(F_Hist,levels= c(1,0))),
              alpha=0.15) + 
  geom_line(aes(xfh,predggfh_mem[,1],
                color=factor(F_Hist,
                             levels = c(1,0)),
                linetype=factor(F_Hist,
                                levels = c(1,0))),
            size=1) + 
  theme_classic2()+xmarks+
  ylab("Predicted log(ECog)") + 
  xlab(xlab)+
  theme(legend.justification=c(1,0), 
        legend.position=c(0.95,.67),
        legend.spacing = unit(0.2,"cm"),
        legend.text=element_text(size=textSize),
        legend.title = element_blank(),
        legend.title.align=0,
        text = element_text(size = textSize),
        plot.margin = PM)+
  scale_color_discrete(labels = c("yes","no"))+
  scale_linetype_discrete(labels = c("yes","no"))+
  coord_cartesian(xlim = xlim, ylim = c(limin,limax), expand = FALSE,
                  default = FALSE, clip = "on")+
  guides(fill = FALSE,
         linetype=FALSE,
         color=FALSE)
if (BW==1) {
  Fh_mem <- Fh_mem + scale_color_grey(start = 0, end = .8) + scale_fill_grey(start = 0, end = .8)
}

FigureList[[5]]<-Fh_mem

#depressive symptoms
Dpr_mem <- ggplot(data = newDFdepr)+ 
  geom_ribbon(aes(xdpr,ymin=predggdpr_mem[,2],ymax=predggdpr_mem[,3],
                  group=factor(depression_01,levels = c(1,0,-1)),
                  fill=factor(depression_01,levels = c(1,0,-1))),
              alpha=0.15) + 
  geom_line(aes(xdpr,predggdpr_mem[,1],
                color=factor(depression_01,levels = c(1,0,-1)),
                linetype=factor(depression_01,levels = c(1,0,-1))),
            size=1) + 
  theme_classic2()+xmarks+
  ylab("Predicted log(ECog)") + 
  xlab(xlab)+
  theme(legend.justification=c(1,0), 
        legend.position=c(0.95,0.6),
        legend.direction = "vertical",
        legend.text=element_text(size=textSize),
        legend.title = element_text(size=textSize),
        legend.text.align=0,
        legend.title.align=0,
        text = element_text(size = textSize),
        plot.margin = PM)+
  scale_linetype_discrete(name="Depressive symptoms")+
  scale_color_discrete(name="Depressive symptoms")+
  coord_cartesian(xlim = xlim, ylim = c(limin,limax), expand = FALSE,
                  default = FALSE, clip = "on")+
  guides(fill = FALSE,
         linetype=FALSE,
         color=FALSE)
if (BW==1) {
  Dpr_mem <- Dpr_mem + scale_color_grey(start = 0, end = .8) + scale_fill_grey(start = 0, end = .8)
}

FigureList[[6]]<-Dpr_mem

###############################################################################
###############################################################################
###############################################################################
#plots for executive function
###############################################################################
xlab<-"Executive function"

#base model with age only
newDFage<-cbind(newDFage,predggba)
range<-c(1:20)
Ba <- ggplot(data = newDFage[range,])+
  geom_ribbon(aes(ex_function,ymin=lwr,ymax=upr,
                  group=factor(AGE_75_d,levels = c(1,0,-1)),
                  fill=factor(AGE_75_d,levels = c(1,0,-1))),
              alpha=0.15)+
  geom_line(aes(ex_function,fit,
                color=factor(AGE_75_d,
                             levels = c(1,0,-1)),
                linetype=factor(AGE_75_d,
                                levels = c(1,0,-1))),
            size=1)+ 
  theme_classic2()+xmarks+
  ylab("Predicted log(ECog)")+
  xlab("Executive function")+
  theme(legend.justification=c(0,0), 
        legend.position="top",#c(0.95,0.6),
        legend.direction = "horizontal",
        legend.text=element_text(size=textSize),
        legend.text.align=1,
        legend.title = element_text(size = textSize,face = "bold"),
        text = element_text(size = textSize),
        plot.margin = PM)+
  scale_color_discrete(name="Modifier: Age",
    labels = c("85","75","65"))+
  scale_linetype_discrete(name="Modifier: Age",
    labels = c("85","75","65"))+
  coord_cartesian(xlim = xlim, ylim = c(limin,limax), expand = FALSE,
                  default = FALSE, clip = "on")+
  guides(fill = FALSE)

if (BW==1) {
  Ba <- Ba + scale_color_grey(name="Modifier: Age",
                              labels = c("85","75","65"),start = 0, end = .9) + scale_fill_grey(name="Modifier: Age",start = 0, end = .9)+coord_cartesian(xlim = xlim, ylim = c(limin,limax), expand = FALSE,
                                                                                                                                                          default = FALSE, clip = "on")
}

FigureList[[7]]<-Ba

#race/ethnicity
newDFrace<-cbind(newDFrace,predggra)
Ra<-ggplot(data = newDFrace[-c(14,21,28),])+
  geom_ribbon(aes(ex_function,ymin=lwr,ymax=upr,
                  group=race,fill=race),
              alpha=0.15)+
  geom_line(aes(ex_function,fit,
                color=race,
                linetype=race),
            size=1)+ 
  theme_classic2()+xmarks+
  ylab("Predicted log(ECog)")+
  xlab("Executive function")+
  theme(legend.justification=c(0,0), 
        legend.position="top",#c(.95,0.55),
        legend.title = element_text(size = 11,face = "bold"),
        legend.spacing = unit(.1, 'cm'),
        legend.direction = "horizontal",
        legend.text=element_text(size=textSize),
        legend.text.align=0,
        legend.title.align=0,
        text = element_text(size = textSize),
        plot.margin = PM,legend.key.width = unit(.35,'cm'))+
  scale_color_discrete(name="Modifier: Race/Ethnicity")+
  scale_linetype_discrete(name="Modifier: Race/Ethnicity")+
  coord_cartesian(xlim = xlim, ylim = c(limin,limax), expand = FALSE,
                  default = FALSE, clip = "on")+
  guides(fill = FALSE)

if (BW==1) {
  Ra <- Ra + scale_color_grey(name="Modifier: Race/Ethnicity",start = 0, end = .90) + scale_fill_grey(start = 0, end = .90) +
    scale_linetype_discrete(name="Modifier: Race/Ethnicity")+ guides(fill = FALSE)
}

FigureList[[8]]<- Ra

#gender
Ge<-ggplot(data = newDFgender)+
  geom_ribbon(
    aes(xge,
        ymin=predggge[,2],
        ymax=predggge[,3],
        group=factor(GENDER,levels = c("Woman","Man")),
        fill=factor(GENDER,levels = c("Woman","Man"))),
    alpha=0.15)+
  geom_line(
    aes(xge,
        predggge[,1],
        color=factor(GENDER,levels = c("Woman","Man")),
        linetype=factor(GENDER,levels = c("Woman","Man"))),
    size=1)+ 
  theme_classic2()+xmarks+
  ylab("Predicted log(ECog)")+
  xlab("Executive function")+
  theme(legend.justification=c(0,0), 
        legend.position="top",#c(0.95,0.60),
        legend.spacing = unit(.1,"cm"),
        legend.direction = "horizontal",
        legend.text=element_text(size=textSize),
        legend.title.align=0,
        legend.title = element_text(size = textSize,face = "bold"),
        text = element_text(size = textSize),
        plot.margin = PM)+
  scale_linetype_discrete(name="Modifier: Gender",
    labels=c("Women","Men"))+
  scale_color_discrete(name="Modifier: Gender",
    labels=c("Women","Men"))+
  coord_cartesian(xlim = xlim, ylim = c(limin,limax), expand = FALSE,
                  default = FALSE, clip = "on")+
  guides(fill = FALSE)

if (BW==1) {
  Ge <- Ge + scale_color_grey(name="Modifier: Gender",
                              labels=c("Women","Men"),start = 0, end = .7) + scale_fill_grey(name="Modifier: Gender",start = 0, end = .7)
}

FigureList[[9]]<-Ge

#education duration
newDFedu<-cbind(newDFedu,predgged)
range<-c(1:5,8:21)
Ed <- ggplot(data = newDFedu[range,])+ 
  geom_ribbon(aes(ex_function,ymin=lwr,ymax=upr,
                  group=factor(yrEDU),
                  fill=factor(yrEDU)),
              alpha=0.15) +
  geom_line(aes(ex_function,fit,
                color=factor(yrEDU),
                linetype=factor(yrEDU)),
            size=1) + 
  theme_classic2()+xmarks+
  ylab("Predicted log(ECog)") + 
  xlab("Executive function")+
  theme(legend.justification=c(0,0), 
        legend.position="top",#c(.95,0.6),
        legend.direction = "horizontal",
        legend.text=element_text(size=textSize),
        legend.text.align=0,
        legend.title.align=1,
        legend.title = element_text(size = textSize,face = "bold"),
        text = element_text(size = textSize),
        plot.margin = PM)+
  scale_color_discrete(name="Modifier: Educational attainment (in years)",
                       labels = c("8 ","12 ","16 "))+
  scale_linetype_discrete(name="Modifier: Educational attainment (in years)", 
                          labels = c("8 ","12 ","16 "))+
  coord_cartesian(xlim = xlim, ylim = c(limin,limax), expand = FALSE,
                  default = FALSE, clip = "on")+
  guides(fill = FALSE)

if (BW==1) {
  Ed <- Ed + scale_color_grey(name="Modifier: Educational attainment (in years)",
                              labels = c("8 ","12 ","16 "),start = 0, end = .8) + scale_fill_grey(name="Modifier: Educational attainment (in years)",
                                                                                                  labels = c("8 ","12 ","16 "),start = 0, end = .8)
}
FigureList[[10]]<-Ed

#Family history of dementia
Fh <- ggplot(data = newDFfhist)+
  geom_ribbon(aes(xfh,ymin=predggfh[,2],ymax=predggfh[,3],
                  group=factor(F_Hist,levels = c(1,0)),
                  fill=factor(F_Hist,levels= c(1,0))),
              alpha=0.15) + 
  geom_line(aes(xfh,predggfh[,1],
                color=factor(F_Hist,
                             levels = c(1,0)),
                linetype=factor(F_Hist,
                                levels = c(1,0))),
            size=1) + 
  theme_classic2()+xmarks+
  ylab("Predicted log(ECog)") + 
  xlab(xlab)+
  theme(legend.justification=c(0,0), 
        legend.position="top",#c(0.95,.6),
        legend.direction = "horizontal",
        legend.spacing = unit(0.2,"cm"),
        legend.text=element_text(size=textSize),
        legend.title.align=0,
        legend.title = element_text(size = textSize,face = "bold"),
        text = element_text(size = textSize),
        plot.margin = PM)+
  scale_color_discrete(name="Modifier: Familly history of dementia",labels = c("yes","no"))+
  scale_linetype_discrete(name="Modifier: Familly history of dementia",
                          labels = c("yes","no"))+
  coord_cartesian(xlim = xlim, ylim = c(limin,limax), expand = FALSE,
                  default = FALSE, clip = "on")+
  guides(fill = FALSE)

if (BW==1) {
  Fh <- Fh + scale_color_grey(name="Modifier: Familly history of dementia",labels = c("yes","no"),start = 0, end = .7) + scale_fill_grey(name="Modifier: Familly history of dementia",labels = c("yes","no"),start = 0, end = .7)
}
FigureList[[11]]<-Fh

#depressive symptoms
newDFdepr<-cbind(newDFdepr,predggdpr)
Dpr <- ggplot(data = newDFdepr[1:20,])+ 
  geom_ribbon(aes(ex_function,ymin=lwr,ymax=upr,
                  group=factor(depression_01,levels = c(1,0,-1)),
                  fill=factor(depression_01,levels = c(1,0,-1))),
              alpha=0.15) + 
  geom_line(aes(ex_function,fit,
                color=factor(depression_01,levels = c(1,0,-1)),
                linetype=factor(depression_01,levels = c(1,0,-1))),
            size=1) + 
  theme_classic2()+xmarks+
  ylab("Predicted log(ECog)") + 
  xlab(xlab)+
  theme(legend.justification=c(0,0), 
        legend.position="top",#c(0.95,0.6),
        legend.direction = "horizontal",
        legend.text=element_text(size=textSize),
        legend.text.align=0,
        legend.title.align=0,
        legend.title = element_text(size = textSize,face = "bold"),
        text = element_text(size = textSize),
        plot.margin = PM)+
  scale_linetype_discrete(name="Modifier: Depressive symptoms")+
  scale_color_discrete(name="Modifier: Depressive symptoms")+
  coord_cartesian(xlim = xlim, ylim = c(limin,limax), expand = FALSE,
                  default = FALSE, clip = "on")+
  guides(fill = FALSE)
#        legend.title = element_text(size = textSize,face = "bold"),
if (BW==1) {
  Dpr <- Dpr + scale_color_grey(name="Modifier: Depressive symptoms",start = 0, end = .8) + scale_fill_grey(name="Modifier: Depressive symptoms",start = 0, end = .8)
}
FigureList[[12]]<-Dpr

